// demos/simpleclicker/react/recompose/src/clicker.js
import React from 'react'
import {withState} from 'recompose'

const enhance = withState('count', 'more', 3)
const Clicker = enhance(({count, more}) => (
  <div>
    <p>{count} bottles of beer on the wall</p>
    <button onClick={() => more(n => n + 1)}>Buy more</button>
  </div>
))

export default Clicker

// demos/simpleclicker/angular/javascript/src/clicker.js
import {Component} from '@angular/core'

let Clicker = Component({
  selector: '#app',
  template: `
    <p>{{count}} bottles of beer on the wall</p>
    <button (click)="more()">Buy more</button>
  `
}).Class({
  constructor: function () {
    this.count = 3
  },
  more () {
    this.count++
  }
})

export default Clicker
