// demos/simpleclicker/react/es6/src/clicker.js
import React from 'react'

class Clicker extends React.Component {
  constructor() {
    super()
    this.state = {count: 3}
    this.more = ()=> this.setState({count:this.state.count+1})
  }
  render() {
    return <div>
      <p>{this.state.count} bottles of beer on the wall</p>
      <button onClick={this.more}>Buy more</button>
    </div>
  }
}

export default Clicker

// demos/simpleclicker/angular/javascript/src/clicker.js
import {Component} from '@angular/core'

let Clicker = Component({
  selector: '#app',
  template: `
    <p>{{count}} bottles of beer on the wall</p>
    <button (click)="more()">Buy more</button>
  `
}).Class({
  constructor: function () {
    this.count = 3
  },
  more () {
    this.count++
  }
})

export default Clicker
