// demos/localstorage/react/es6class/src/voter.js
import React from 'react'
import classNames from 'classnames'

let teams = ["Valor","Mystic","Instinct"]

class Voter extends React.Component {
  constructor() {
    super()
    this.state = {team: +(localStorage.getItem('JSCOMPVOTE') || 1)}
  }
  vote(team) {
    this.setState({team})
    localStorage.setItem('JSCOMPVOTE',team)
  }
  render() {
    return <div>
      {teams.map((t,n)=> <button key={n}
        className={classNames({active:this.state.team === n})}
        onClick={this.vote.bind(this,n)}>{t}</button>
      )}
    </div>
  }
}

export default Voter

// demos/localstorage/angular/typescript/src/voter.ts
import {Component} from '@angular/core';

@Component({
  selector: '#app',
  template: `
    <button *ngFor="let t of teams; let i = index" (click)="vote(i)" [class.active]="team===i">{{t}}</button>
  `
})
export class Voter {
  teams = ["Valor","Mystic","Instinct"]
  team = +(localStorage.getItem('JSCOMPVOTE') || 1)
  vote(x) {
    this.team = x;
    localStorage.setItem('JSCOMPVOTE',x)
  }
}
