// demos/interval/angular/typescript/src/singer.ts
import {Component, AfterViewInit} from '@angular/core';

let lyrics = ["Eeexiiit light","Eeenteeer niight","Taaake my haaand","We're off to never never land"]

@Component({
  selector: 'singer',
  template: `{{line}}`
})
export class Singer implements AfterViewInit {
  pos = 0
  get line() {
    return lyrics[this.pos]
  }
  ngAfterViewInit() {
    setInterval(()=> this.pos = (this.pos+1)%4, 1500)
  }
}

// demos/interval/react/es6/src/singer.js
import React from 'react'

let lyrics = ['Eeexiiit light', 'Eeenteeer niight', 'Taaake my haaand', "We're off to never never land"]

class Singer extends React.Component {
  constructor () {
    super()
    this.state = {pos: 0}
    setInterval(() => this.setState({pos: (this.state.pos + 1) % 4}), 1500)
  }
  render () {
    return <div>{lyrics[this.state.pos]}</div>
  }
}

export default Singer
