// demos/composition/angular/typescript/src/form.ts
import {Component} from '@angular/core'

@Component({
  selector: '#app',
  template: `
    <field instruction="Enter name" (submission)="onSubmission($event)"></field>
    <p>Submitted name: {{submission}}</p>
  `
})
export class Form {
  submission: string = 'Steve'
  onSubmission(txt) {
    this.submission = txt;
  }
}

// demos/composition/react/createclass/src/form.js
import React from 'react'
import Field from './field'

let Form = React.createClass({
  getInitialState: ()=> ({submission:'Steve'}),
  onSubmission(txt) { this.setState({submission:txt}) },
  render() {
    return (
      <div>
        <Field instruction="Enter name" onSubmission={this.onSubmission} />
        <p>Submitted value: {this.state.submission}</p>
      </div>
    )
  }
})

export default Form
