// demos/twoway/react/vanilla/src/phonebooth.js
import React from 'react'

let Phonebooth = React.createClass({
  getInitialState: ()=> ({name:'Steve'}),
  change() {
    this.setState({name:'Batman'})
  },
  type(e) {
    this.setState({name:e.target.value})
  },
  render() {
    let name = this.state.name
    return <div>
      <div><input onChange={this.type} value={name} /></div>
      <p>Your name is {name}</p>
      <button onClick={this.change}>Put on costume</button>
    </div>
  }
})

export default Phonebooth

// demos/twoway/angular/typescript/src/phonebooth.ts
import {Component,ViewChild} from '@angular/core';

@Component({
  selector: '#app',
  template: `
    <input #field [(ngModel)]="name"><br/>
    <p>Your name is {{name}}.</p>
    <button (click)="change()">Put on costume</button>
  `
})
export class Phonebooth {
  @ViewChild('field') input
  name = 'Steve'
  change() {
    this.name = 'Batman'
    this.input.nativeElement.focus()
  }
}
