// demos/composition/react/vanilla/src/confirm.js
import React from 'react'

let Confirm = React.createClass({
  getInitialState: ()=> ({mode:'waiting'}),
  maybe() { this.setState({mode:'confirm'}) },
  changedmymind() { this.setState({mode:'waiting'}) },
  yesimsure() {
    this.props.confirm();
    this.setState({mode:'waiting'})
  },
  render() {
    return this.state.mode !== 'confirm'
    ? <button onClick={this.maybe} disabled={this.props.disabled}>Submit</button>
    : <span>
        <button onClick={this.changedmymind}>Cancel</button>
        <button onClick={this.yesimsure}>Confirm</button>
      </span>
  }
})

export default Confirm

// demos/composition/angular/typescript/src/confirm.ts
import {Component,Input,Output,EventEmitter} from '@angular/core';

@Component({
  selector: 'confirm',
  template: `
    <span *ngIf="mode !== 'confirm'">
      <button (click)="maybe()" [disabled]="mode === 'disabled'">Submit</button>
    </span>
    <span *ngIf="mode === 'confirm'">
      <button (click)="changedmymind()">Cancel</button>
      <button (click)="yesimsure()">Confirm</button>
    </span>
  `
})
export class Confirm {
  mode: string = 'waiting'
  @Output() confirm = new EventEmitter<void>()
  @Input() set disabled(bool: boolean){
    this.mode = bool ? 'disabled' : 'waiting'
  }
  maybe() { this.mode = 'confirm' }
  changedmymind() { this.mode = 'waiting' }
  yesimsure() {
    this.confirm.emit()
    this.mode = 'waiting'
  }
}
