// demos/composition/react/createclass/src/field.js
import React from 'react'
import Confirm from './confirm'

let Field = React.createClass({
  getInitialState: () => ({field: ''}),
  onConfirm () {
    this.props.onSubmission(this.state.field)
    this.setState({field: ''})
  },
  onChange (e) {
    this.setState({field: e.target.value})
  },
  render () {
    return (
      <div>
        {this.props.instruction}: <input value={this.state.field} onChange={this.onChange} />
        <Confirm disabled={!this.state.field} confirm={this.onConfirm} />
      </div>
    )
  }
})

export default Field

// demos/composition/angular/typescript/src/field.ts
import {Component,ViewChild,EventEmitter,Input,Output} from '@angular/core'

@Component({
  selector: 'field',
  template: `
    {{instruction}}: <input #field (input)="0">
    <confirm (confirm)="onConfirm()" [disabled]="!field.value.length"></confirm>
  `
})
export class Field {
  @ViewChild('field') input: any
  @Input() instruction: string
  @Output() submission = new EventEmitter<string>()
  onConfirm() {
    this.submission.emit(this.input.nativeElement.value)
    this.input.nativeElement.value = ''
  }
}
