// demos/firebase/angular/typescript/src/battle.ts
import {Component} from '@angular/core';

import {subscribe,nudge} from '../../../nudger.js'

@Component({
  selector: 'battle',
  template: `
    <div *ngIf="loaded">
      <button *ngFor="let t of teams" (click)="nudge(t)">
        {{t}} ({{status[t]}})
      </button>
    </div>
    <div *ngIf="!loaded">
      Fetching data...
    </div>
  `
})
export class Battle {
  loaded = false
  status = {}
  teams = []
  nudge:Function = nudge
  constructor() {
    subscribe(val=>{
      this.status = val
      this.teams = Object.keys(this.status).sort()
      this.loaded = true
    })
  }
}

// demos/firebase/react/es6/src/battle.js
import React from 'react'
import {subscribe, nudge} from '../../../nudger'

class Battle extends React.Component {
  constructor () {
    super()
    this.state = {
      loaded: false,
      status: {},
      teams: []
    }
    subscribe(val => {
      this.setState({
        loaded: true,
        teams: Object.keys(val).sort(),
        status: val
      })
    })
  }

  render () {
    const teamButtons = this.state.teams &&
      this.state.teams.map((team, i) =>
        <button key={`${team}${i}`} onClick={nudge.bind(null, team)}>
          {team} {this.state.status[team]}
        </button>
      )
    return (
      <div>{
        this.state.loaded
          ? teamButtons
          : 'Fetching data...'
        }
      </div>
    )
  }
}

export default Battle
